# Generated by Django 6.0.6 on 2026-06-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sushi Restaurant', max_length=200)),
                ('address', models.TextField(default='')),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('working_hours', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'restaurant settings',
            },
        ),
    ]
