# Generated by Django 6.0.6 on 2026-07-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_available', 'category'], name='catalog_pro_is_avai_19a49a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured'], name='catalog_pro_is_feat_94b8d5_idx'),
        ),
    ]
